import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Hero from "@/components/Hero";
import ParticlesContainer from "@/components/ParticlesContainer";
import { Locale, i18n } from "@/i18n.config";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className={`antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
